# Generated by Django 4.0 on 2022-01-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='Sanjay0',
            new_name='Sanjay',
        ),
    ]
