# Generated by Django 4.0 on 2022-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_sanjay0_transfers_sanjay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='Sanjay',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='transfers',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
